### ISSUE TITLE
App unable to run

### ISSUE THREAD

**Issue by SpecPo** [Riotphobia/Netherblade#2]
executing:
java -jar Netherblade-1.21-jar-with-dependencies.jar

yields:

[12 Feb 2023 04:16:08] [INTERNAL] No log.properties present
Unable to modify permitted HTTP methods, exiting (1).
[12 Feb 2023 04:16:08] [ERROR] java.lang.NoSuchFieldException: modifiers
        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
        at com.hawolt.util.ReflectHttp.enable(ReflectHttp.java:18)
        at com.hawolt.Main.main(Main.java:24)

Is there a setting or something that has to be modified to run the app ?

**Comment by SpecPo** [comment]
Issue stems from using java 17, due to depreceation of java.lang.SecurityManager, downgrade to java 8 solves it.

**Comment by hawolt** [comment]
The repository states that a software requirement is Java 8, I'll make it more specific that Java 17+ will break functionallity.
I will need to double check how higher versions behave, maybe a few extra lines can this issue.

**Comment by SpecPo** [comment]
Yes, the ubiquitous saying RTFM comes to my mind.

**Comment by SpecPo** [comment]
Yes, the ubiquitous saying RTFM comes to my mind.

**Comment by SpecPo** [comment]
Yes, the ubiquitous saying RTFM comes to my mind.

**Comment by hawolt** [comment]
added some information when launched with an uncompatible Java version for now
